services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel-db-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hotel_guest_service_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: hotel-mailpit-container
    ports:
      - "1026:1025"
      - "8026:8025"
    restart: unless-stopped

volumes:
  postgres_data: