spring:
  application:
    name: hotel-guest-service-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ email, profile ]

logging:
  level:
    root: INFO
    com.jerzymaj.hotel_guest_service_system: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 604800000
  http:
    allowed-origins: "${ALLOWED_ORIGIN:http://localhost:5173}"
  support:
    email: ${SUPPORT_EMAIL:tech@hotel.com}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    phone-number: ${TWILIO_PHONE_NUMBER}
  oauth2:
    redirect-uri: "${OAUTH2_REDIRECT_URI:http://localhost:5173/oauth2/redirect}"

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_guest_service_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: localhost
    port: 1026
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

